<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" 
	xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ImportGroup Label="PropertySheets">
		<Import Project="./3dsmax.common.settings.props" Condition="$(HasImportedCommonProps) != '1'" />
	</ImportGroup>

	<PropertyGroup Label="UserMacros">
		<PxrUsdRoot Condition="'$(MaxUsdDevKit)'!='' and '$(PxrUsdRoot)'==''">$(MaxUsdDevKit)\Pixar_USD</PxrUsdRoot>
		<PxrUsdRoot Condition="'$(VersionTarget)'&gt;'2025' and '$(PxrUsdRoot)'==''">$(Artifacts)$(VersionTarget)\Pixar_USD</PxrUsdRoot>
		<PxrUsdRoot Condition="'$(VersionTarget)'&lt;='2025' and '$(PxrUsdRoot)'==''">$(Artifacts)$(VersionTarget)\Pixar_USD\Release</PxrUsdRoot>
		<Pixar_USDInc>$(PxrUsdRoot)\include</Pixar_USDInc>
		<Pixar_USDLib>$(PxrUsdRoot)\lib</Pixar_USDLib>
		<AdskAssetResolverDir Condition="'$(MaxUsdDevKit)'!='' and '$(AdskAssetResolverDir)'==''">$(MaxUsdDevKit)\adskassetresolver</AdskAssetResolverDir>
		<AdskAssetResolverDir Condition="'$(VersionTarget)'&gt;'2025' and '$(AdskAssetResolverDir)'==''">$(Artifacts)$(VersionTarget)\adskassetresolver\RelWithDebInfo</AdskAssetResolverDir>
		<AdskAssetResolverInc Condition="'$(VersionTarget)'&gt;'2025'">$(AdskAssetResolverDir)\include</AdskAssetResolverInc>
		<AdskAssetResolverLib Condition="'$(VersionTarget)'&gt;'2025'">$(AdskAssetResolverDir)\lib</AdskAssetResolverLib>
		<AdskAssetResolverBin Condition="'$(VersionTarget)'&gt;'2025'">$(AdskAssetResolverDir)\bin</AdskAssetResolverBin>
		<!-- With OpenUSD 24.11 and up, Python is no longer included, only the boost/python headers are -->
		<BoostVersion Condition="'$(VersionTarget)'=='2025'">1_81</BoostVersion>
		<BoostVersion Condition="'$(VersionTarget)'=='2024'">1_76</BoostVersion>
		<BoostVersion Condition="'$(VersionTarget)'&lt;'2024'">1_70</BoostVersion>
		<BoostInc Condition="'$(VersionTarget)'&gt;'2025' and '$(BoostInc)'==''">$(Pixar_USDInc)\pxr\external</BoostInc>
		<BoostInc Condition="'$(VersionTarget)'&lt;='2025' and '$(BoostInc)'==''">$(PxrUsdRoot)\include\boost-$(BoostVersion)</BoostInc>
		<BoostLib Condition="'$(VersionTarget)'&lt;='2025' and '$(BoostLib)'==''">$(Pixar_USDLib)</BoostLib>
		<BoostLibToolSet Condition="'$(VersionTarget)'&lt;'2025'">vc141</BoostLibToolSet>
		<BoostLibToolSet Condition="'$(VersionTarget)'&gt;='2025'">vc142</BoostLibToolSet>
		<TBBDir Condition="'$(TBBDir)'==''">$(PxrUsdRoot)</TBBDir>
		<TBBInclude>$(TBBDir)\include</TBBInclude>
		<TBBLib>$(TBBDir)\lib</TBBLib>
		<PythonLocation Condition="'$(MaxUsdDevKit)'!=''and '$(PythonLocation)'==''">$(MaxUsdDevKit)\Python</PythonLocation>
		<PythonLocation Condition="'$(PythonLocation)'==''">$(Artifacts)$(VersionTarget)\Python</PythonLocation>
		<PythonInc>$(PythonLocation)\Include</PythonInc>
		<PythonLibs>$(PythonLocation)\libs</PythonLibs>
		<PythonVersion Condition="'$(VersionTarget)'&gt;'2026'">313</PythonVersion>
		<PythonVersion Condition="'$(VersionTarget)'&gt;='2025' and '$(VersionTarget)'&lt;='2026'">311</PythonVersion>
		<PythonVersion Condition="'$(VersionTarget)'=='2024'">310</PythonVersion>
		<PythonVersion Condition="'$(VersionTarget)'=='2022'">37</PythonVersion>
		<PyOpenGLDir Condition="'$(PyOpenGLDir)'==''">$(Artifacts)$(VersionTarget)\PyOpenGL</PyOpenGLDir>
	</PropertyGroup>
	<PropertyGroup>
	    <ExternalIncludePath>$(Pixar_USDInc);$(VC_IncludePath);$(WindowsSDK_IncludePath)</ExternalIncludePath>
	</PropertyGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<!-- Starting with 3dsMax 2024, one USD version per 3dsMax release. -->
			<PreprocessorDefinitions Condition="$(VersionTarget)&gt;=2025">USD_VERSION_23_08;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="'$(VersionTarget)'&gt;'2025'">;USD_CURVES_SUPPORTED;%(PreprocessorDefinitions)</PreprocessorDefinitions>
		</ClCompile>
		<ClCompile>
			<AdditionalIncludeDirectories>$(SolutionDir);$(BoostInc);$(TBBInclude);$(PythonInc);$(Pixar_USDInc);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
			<PreprocessorDefinitions>_SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING;NOMINMAX=;TBB_SUPPRESS_DEPRECATED_MESSAGES;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="$(VersionTarget)&lt;=2025">BOOST_ALL_NO_LIB;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<PreprocessorDefinitions Condition="$(VersionTarget)&lt;=2022">_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<DisableSpecificWarnings>4003;%(DisableSpecificWarnings)</DisableSpecificWarnings>
			<AdditionalOptions Condition="$(VersionTarget)&lt;=2022">/experimental:external /external:I $(Pixar_USDInc)\include /external:W0 %(AdditionalOptions)</AdditionalOptions>
			<AdditionalOptions Condition="$(VersionTarget)&gt;=2024">/Zc:__cplusplus</AdditionalOptions>
		</ClCompile>
		<ClCompile Condition="'$(Configuration)'=='$(ConfigHybrid)'">
			<!-- Optimization is disabled for all configs except Release -->
			<Optimization>Disabled</Optimization>
			<PreprocessorDefinitions>;_HYBRID;IS_HYBRID;SECURE_SCL=0;%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<!--
			Boost does not like us having runtime checks (RTC) with non debug build.
			Thus Microsoft documentation only states that Optimizations needs to be disabled (as done for hybrid), doing no mention of debug vs release build.
			Disable RTC as it the only way to build hybrid.
			-->
			<BasicRuntimeChecks>Default</BasicRuntimeChecks>
		</ClCompile>
		<Link>
			<AdditionalLibraryDirectories>$(Pixar_USDLib);$(BoostLib);$(TBBLib);$(PythonLibs);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>OpenGL32.lib;3dsmax_usd.lib;3dsmax_sdf.lib;3dsmax_js.lib;3dsmax_pcp.lib;3dsmax_tf.lib;3dsmax_ar.lib;3dsmax_arch.lib;3dsmax_garch.lib;3dsmax_gf.lib;3dsmax_glf.lib;3dsmax_hd.lib;3dsmax_hdSt.lib;3dsmax_hdx.lib;3dsmax_hf.lib;3dsmax_kind.lib;3dsmax_sdr.lib;3dsmax_plug.lib;3dsmax_trace.lib;3dsmax_usdGeom.lib;3dsmax_usdImaging.lib;3dsmax_usdImagingGL.lib;3dsmax_usdLux.lib;3dsmax_vt.lib;3dsmax_work.lib;3dsmax_usdUtils.lib;3dsmax_usdShade.lib;3dsmax_usdUI.lib;3dsmax_usdSkel.lib;%(AdditionalDependencies)</AdditionalDependencies>
			
			<AdditionalDependencies Condition="$(VersionTarget)&lt;=2025">%(AdditionalDependencies);boost_python$(PythonVersion)-$(BoostLibToolSet)-mt-x64-$(BoostVersion).lib</AdditionalDependencies>
			<AdditionalDependencies Condition="$(VersionTarget)&gt;2025">%(AdditionalDependencies);3dsmax_python.lib;3dsmax_boost.lib;3dsmax_ts.lib</AdditionalDependencies>
			<AdditionalDependencies Condition="$(VersionTarget)&lt;=2026">%(AdditionalDependencies);3dsmax_ndr.lib</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
</Project>
